"""社内テンプレートのパターン検証用デッキ定義。"""

from copy import deepcopy

from diagram_specs import AWS_MULTIAZ_EXAMPLE, AWS_SIMPLE_EXAMPLE

PATTERN_DECK = {
    "meta": {
        "title": "社内スライドパターン検証ギャラリー",
        "footer": "社内スライドパターン検証ギャラリー",
        "date": "2026年7月",
        "author": "業務改善検討チーム",
    },
    "slides": [
        {
            "type": "title",
            "pattern": "title",
            "title": "社内スライド\nパターンライブラリ",
            "subtitle": "意思決定からシステム構成まで、17の標準レイアウトを検証",
        },
        {
            "type": "bullets",
            "pattern": "agenda / bullets",
            "kicker": "検証方針",
            "title": "LLMは構造化、rendererは提出品質を担う",
            "bullets": [
                ("文言・項目・強調は content 側に寄せ、座標や余白は renderer 側に閉じ込める", None),
                ("汎用エンジン化しすぎず、よく使うスライド種別をカタログとして増やす", None),
                ("PowerPoint 実レンダリングと機械検知を品質ゲートにして、崩れを早期に発見する", None),
            ],
        },
        {
            "type": "cards",
            "pattern": "editorial key points",
            "style": "editorial",
            "kicker": "要点整理",
            "title": "判断に必要な4つの要点を、読み順に沿って整理する",
            "cards": [
                ("目的", "何を判断してほしいかを1文で示し、読み手の視点を揃える。"),
                ("現状", "事実・制約・既に分かっていることを短く置く。"),
                ("示唆", "現状から言えることを、推測と事実を分けて整理する。"),
                ("次アクション", "誰が・いつまでに・何をするかを明確にする。"),
            ],
        },
        {
            "type": "cards",
            "pattern": "KPI metric cards",
            "style": "metrics",
            "kicker": "KPIスナップショット",
            "title": "KPIは数値を主役にし、判断材料を添える",
            "cards": [
                ("作成時間 -72%", "週次報告の作成時間が平均45分から13分に短縮。下書き作成の自動化が主因。"),
                ("手直し 8分", "生成後の確認と語尾修正に平均8分。テンプレート崩れは検出なし。"),
                ("再利用率 64%", "一度作った構造化データを翌週も流用でき、定型資料ほど効果が高い。"),
            ],
        },
        {
            "type": "twocol",
            "pattern": "2-column comparison",
            "kicker": "Before / After",
            "title": "導入前後の違いを、同じ観点で比較する",
            "left": {
                "heading": "導入前",
                "bullets": [
                    "担当者ごとにスライド構成がばらつき、レビュー観点も揃わない",
                    "グラフや表の貼り付け後に、余白・フォント・禁則を手作業で直す",
                    "過去資料をコピーして使うため、古い文言や注記が残りやすい",
                ],
            },
            "right": {
                "heading": "導入後",
                "bullets": [
                    "入力schemaに沿って文言を作るため、構成の揺れを抑えられる",
                    "rendererが余白・フォント・描画順を決め、提出前の確認に集中できる",
                    "品質ゲートで重なりやはみ出しを検知し、修正箇所を特定しやすい",
                ],
            },
        },
        {
            "type": "table",
            "pattern": "comparison table",
            "kicker": "方式比較",
            "title": "選定理由と見送り理由を、同じ粒度で比較する",
            "columns": ["方式", "向いている用途", "強み", "注意点"],
            "col_widths": [2.0, 3.1, 3.1, 4.0],
            "rows": [
                ["renderer カタログ", "社内標準資料・定型報告", "品質を詰めた型を再利用できる", "新しい型は実装が必要"],
                ["万能宣言レイアウト", "図の大量バリエーション", "座標指定を減らせる", "エンジンが複雑化しやすい"],
                ["手作業PPT", "一点物の重要提案", "細部まで作り込める", "再現性と量産性が低い"],
            ],
        },
        {
            "type": "chart",
            "pattern": "bar chart",
            "kicker": "効果測定",
            "title": "資料作成時間を最大72%短縮",
            "note": "値は検証用のサンプルデータ。",
            "chart": {
                "categories": ["週次報告", "月次レビュー", "調査サマリ", "役員向け抜粋"],
                "series": [
                    ("従来 (分)", [45, 120, 240, 90]),
                    ("生成後 (分)", [13, 42, 85, 28]),
                ],
            },
        },
        {
            "type": "process",
            "pattern": "process / timeline",
            "kicker": "標準プロセス",
            "title": "資料生成は5つの工程で品質を担保する",
            "steps": [
                {"name": "入力整理", "desc": "目的・読み手・必須メッセージを整理する。", "actor": "人間"},
                {"name": "構造化", "desc": "schemaに沿ってスライド種別と文言を作る。", "actor": "LLM"},
                {"name": "生成", "desc": "rendererがPPTXを決定論的に出力する。", "actor": "コード"},
                {"name": "検証", "desc": "機械検知と目視で崩れを確認する。", "actor": "コード + 人間"},
                {"name": "提出", "desc": "contentを直して再生成し、提出する。", "actor": "人間"},
            ],
            "emph": [3],
        },
        {
            "type": "roadmap",
            "pattern": "roadmap / gantt",
            "kicker": "展開計画",
            "title": "12か月で型の整備から全社標準へ移行する",
            "months": ["4月", "5月", "6月", "7月", "8月", "9月",
                       "10月", "11月", "12月", "1月", "2月", "3月"],
            "phases": [
                {"name": "Phase 1  型の定義", "goal": "主要パターンを選定",
                 "bar": "標準レイアウトを定義", "start": "4月", "end": "5月"},
                {"name": "Phase 2  実装", "goal": "rendererを整備",
                 "bar": "生成・検証機能を実装", "start": "5月", "end": "7月"},
                {"name": "Phase 3  現場検証", "goal": "複数部門で試行",
                 "bar": "パイロット運用", "start": "7月", "end": "10月"},
                {"name": "Phase 4  改善", "goal": "利用結果を反映",
                 "bar": "品質・操作性を改善", "start": "10月", "end": "12月"},
                {"name": "Phase 5  標準化", "goal": "全社手順へ組込",
                 "bar": "標準運用へ移行", "start": "1月", "end": "3月"},
            ],
            "milestones": [
                {"at": "5月", "row": 0, "label": "型レビュー"},
                {"at": "10月", "row": 2, "label": "展開判断"},
                {"at": "3月", "row": 4, "label": "標準化"},
            ],
        },
        {
            "type": "program_roadmap",
            "pattern": "multi-track program roadmap",
            "kicker": "年間プログラム",
            "title": "5つの改善テーマと並行作業を、年間計画として俯瞰する",
            "periods": ["4月", "5月", "6月", "7月", "8月", "9月",
                        "10月", "11月", "12月", "1月", "2月", "3月"],
            "tracks": [
                {
                    "name": "利用部門の拡大",
                    "activities": [
                        {"label": "対象業務の選定", "start": "4月", "end": "6月"},
                        {"label": "追加部門へ展開", "start": "11月", "end": "3月", "emph": True},
                    ],
                },
                {
                    "name": "デザイン標準化",
                    "activities": [
                        {"label": "利用要件の整理", "start": "4月", "end": "6月"},
                        {"label": "共通仕様の策定", "start": "6月", "end": "9月"},
                        {"label": "試行版の検証", "start": "7月", "end": "10月"},
                    ],
                },
                {
                    "name": "運用基盤の再設計",
                    "activities": [
                        {"label": "現状調査", "start": "4月", "end": "5月"},
                        {"label": "移行方針の策定", "start": "6月", "end": "9月"},
                        {"label": "新環境の構築", "start": "7月", "end": "10月"},
                        {"label": "運用リハーサル", "start": "8月", "end": "8月"},
                        {"label": "本番移行", "start": "9月", "end": "10月", "emph": True},
                        {"label": "旧環境の停止", "start": "12月", "end": "3月"},
                    ],
                },
                {
                    "name": "外部サービス連携",
                    "activities": [
                        {"label": "方式検討", "start": "5月", "end": "6月"},
                        {"label": "接続開発", "start": "7月", "end": "9月"},
                        {"label": "段階展開", "start": "10月", "end": "10月"},
                    ],
                },
                {
                    "name": "データ活用基盤",
                    "activities": [
                        {"label": "要件定義", "start": "5月", "end": "6月"},
                        {"label": "基盤構築", "start": "6月", "end": "9月"},
                        {"label": "利用検証", "start": "10月", "end": "11月"},
                        {"label": "全社展開", "start": "12月", "end": "2月", "emph": True},
                    ],
                },
            ],
            "note": "作業の重なりからレーン数を自動計算する。",
        },
        {
            "type": "matrix",
            "pattern": "2-axis matrix",
            "kicker": "優先度整理",
            "title": "提出品質と再利用性から、整備優先度を決める",
            "x_axis": "再利用性 →",
            "y_axis": "↑ 提出品質",
            "target_label": "優先整備",
            "quadrants": ["個別対応", "再利用候補", "品質改善", "優先整備"],
            "points": [
                {"name": "タイトル", "x": 0.18, "y": 0.58},
                {"name": "要点列", "x": 0.72, "y": 0.76, "emph": True},
                {"name": "比較表", "x": 0.68, "y": 0.66, "ly": 0.16},
                {"name": "ロードマップ", "x": 0.44, "y": 0.62, "lx": -1.0},
                {"name": "高密度構成図", "x": 0.35, "y": 0.86},
                {"name": "自由配置図", "x": 0.20, "y": 0.32},
            ],
            "note": "位置づけはテンプレート整備の優先度を示すサンプル。",
        },
        {
            "type": "hub",
            "pattern": "stakeholder hub",
            "kicker": "関係者調整",
            "title": "運用事務局を中心に、6部門の役割をつなぐ",
            "hub": "テンプレート\n運用事務局",
            "ring": [
                {"name": "経営層", "sub": "方針承認", "label": "効果報告", "icon": "icons/fluent/briefcase.png"},
                {"name": "情報システム", "sub": "環境管理", "label": "権限 / 監査", "icon": "icons/fluent/server.png"},
                {"name": "現場部門", "sub": "利用者", "label": "要件 / 評価", "icon": "icons/fluent/team.png"},
                {"name": "法務", "sub": "規程確認", "label": "利用ルール", "icon": "icons/fluent/shield_check.png"},
                {"name": "広報", "sub": "ブランド", "label": "表現基準", "icon": "icons/fluent/send.png"},
                {"name": "外部支援", "sub": "技術相談", "label": "実装支援", "icon": "icons/fluent/toolbox.png"},
            ],
        },
        {
            "type": "org",
            "pattern": "organization chart",
            "kicker": "推進体制",
            "title": "意思決定・実装・展開の責任範囲を明確にする",
            "top": {"name": "ステアリングコミッティ", "sub": "月次で投資・方針を判断"},
            "pm": {"name": "テンプレート整備PM", "sub": "スライド生成基盤の改善責任者"},
            "teams": [
                {"name": "業務設計", "sub": "schema / 用途定義",
                 "members": ["企画 2名", "現場代表 2名"]},
                {"name": "renderer 実装", "sub": "PPTX生成 / 品質ゲート",
                 "members": ["開発 2名", "デザイン 1名"]},
                {"name": "運用展開", "sub": "教育 / レビュー",
                 "members": ["PMO 1名", "各部門窓口"]},
            ],
            "external": {"name": "外部ベンダー", "sub": "技術支援", "label": "助言"},
        },
        {
            "type": "diagram",
            "diagram": deepcopy(AWS_SIMPLE_EXAMPLE),
            "pattern": "simple architecture (inline diagram)",
            "kicker": "構成図",
            "title": "主要コンポーネントとデータの流れを短く示す",
            "note": "AWSアイコンは slidegen/assets/icons/aws/ から読み込む。",
        },
        {
            "type": "diagram",
            "diagram": deepcopy(AWS_MULTIAZ_EXAMPLE),
            "pattern": "dense architecture (inline diagram)",
            "kicker": "高密度構成図",
            "title": "高密度なAWS構成も、グリッド仕様で自動配置する",
        },
        {
            # AWS以外の構成図も、同梱Fluentアイコンを指定して描けることを検証する。
            "type": "diagram",
            "pattern": "fluent icon architecture",
            "kicker": "Fluentアイコン構成図",
            "title": "SSO・監査・バックアップを含む業務システム構成を表現する",
            "note": "同梱のMicrosoft Fluent UIアイコンを使用。ライセンスはslidegen/assets/CREDITS.mdを参照。",
            "diagram": {
                "cols": ["user", "edge", "app", "data"],
                "rows": ["top", "main", "bottom"],
                "nodes": {
                    "client": {"col": "user", "row": "main",
                                "icon": "icons/fluent/desktop.png",
                                "title": "利用者端末", "sub": "社内LAN"},
                    "identity": {"col": "app", "row": "top",
                                 "icon": "icons/fluent/key.png",
                                 "title": "ID基盤"},
                    "fw": {"col": "edge", "row": "main",
                           "icon": "icons/fluent/shield.png",
                           "title": "ファイアウォール"},
                    "web": {"col": "app", "row": "main",
                            "icon": "icons/fluent/server.png",
                            "title": "業務Webサーバ", "sub": "アプリ本体"},
                    "db": {"col": "data", "row": "main",
                           "icon": "icons/fluent/database.png", "title": "DBサーバ"},
                    "log": {"col": "app", "row": "bottom",
                             "icon": "icons/fluent/monitor.png",
                             "title": "ログ収集", "sub": "監査用"},
                    "backup": {"col": "data", "row": "bottom",
                               "icon": "icons/fluent/storage.png",
                               "title": "バックアップ", "sub": "日次保管"},
                },
                "containers": [
                    {"name": "dc", "label": "データセンター",
                     "members": ["fw", "web", "db", "log", "backup"]},
                ],
                "channels": {
                    "identity_lane": ["right_of_col", "app"],
                    "log_lane": ["left_of_col", "app"],
                    "backup_lane": ["outside_container", ["dc", "right"]],
                },
                "edges": [
                    {"from": "client", "to": "fw", "label": "HTTPS",
                     "label_w": 1.0},
                    {"from": "fw", "to": "web"},
                    {"from": "identity", "to": "web",
                     "label": "認証", "label_w": 0.9},
                    {"from": "web", "to": "db", "label": "SQL", "label_w": 0.8},
                    {"from": "web", "to": "log", "exit": "bottom",
                     "enter": "left", "via": ["log_lane"],
                     "label": "監査ログ", "label_w": 1.2,
                     "label_seg": 1, "dash": "dash"},
                    {"from": "db", "to": "backup", "exit": "right",
                     "enter": "right", "via": ["backup_lane"],
                     "label": "日次", "label_w": 0.8, "dash": "dash"},
                ],
            },
        },
        {
            "type": "diagram",
            "pattern": "event-driven fan-out (inline diagram)",
            "kicker": "イベント駆動構成図",
            "title": "受付と処理を分離し、保存・監視へ非同期分岐する",
            "diagram": {
                "cols": ["client", "api", "queue", "worker", "data"],
                "rows": ["top", "main", "bottom"],
                "nodes": {
                    "client": {"col": "client", "row": "main",
                               "icon": "icons/aws/users.png", "title": "業務システム",
                               "sub": "イベント送信元"},
                    "api": {"col": "api", "row": "main",
                            "icon": "icons/fluent/globe.png",
                            "title": "受付API", "sub": "検証・受付"},
                    "queue": {"col": "queue", "row": "main",
                              "icon": "icons/aws/sqs.png", "title": "Amazon SQS",
                              "sub": "処理待ちキュー"},
                    "worker": {"col": "worker", "row": "main",
                               "icon": "icons/fluent/server.png",
                               "title": "非同期ワーカー", "sub": "変換・集計"},
                    "state": {"col": "data", "row": "top",
                              "icon": "icons/aws/dynamodb.png", "title": "DynamoDB",
                              "sub": "処理状態"},
                    "artifact": {"col": "data", "row": "bottom",
                                 "icon": "icons/aws/s3.png", "title": "Amazon S3",
                                 "sub": "成果物"},
                    "monitor": {"col": "worker", "row": "bottom",
                                "icon": "icons/aws/cloudwatch.png", "title": "CloudWatch",
                                "sub": "監視・ログ"},
                },
                "containers": [
                    {"name": "cloud", "label": "AWS Cloud",
                     "members": ["@async", "state", "artifact"]},
                    {"name": "async", "label": "Asynchronous Processing",
                     "members": ["api", "queue", "worker", "monitor"],
                     "color": "navy"},
                ],
                "channels": {},
                "edges": [
                    {"from": "client", "to": "api", "label": "HTTPS"},
                    {"from": "api", "to": "queue", "label": "受付"},
                    {"from": "queue", "to": "worker", "label": "非同期"},
                    {"from": "worker", "to": "state", "label": "状態更新"},
                    {"from": "worker", "to": "artifact", "label": "成果物"},
                    {"from": "worker", "to": "monitor", "dash": "dash"},
                ],
            },
        },
    ],
}
